apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: kmkumarangodemo 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kmkumarangodemo 
    spec:
      containers:
        - name: kmkumarangodemo 
          image: muthukgoappregistry.azurecr.io/kmkumarangodemo 
          ports:
          - containerPort: 80